# Generated by Django 4.2.3 on 2023-08-05 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapi", "0002_waitlist"),
    ]

    operations = [
        migrations.RemoveField(model_name="waitlist", name="url_extension",),
    ]
