# Generated by Django 4.2.3 on 2023-08-05 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapi", "0003_remove_waitlist_url_extension"),
    ]

    operations = [
        migrations.CreateModel(
            name="Email",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email_address", models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="waitlist",
            name="cta",
            field=models.CharField(default="Call to Action", max_length=100),
        ),
        migrations.AddField(
            model_name="waitlist",
            name="headline",
            field=models.CharField(default="Headline", max_length=200),
        ),
        migrations.AddField(
            model_name="waitlist",
            name="hero_url",
            field=models.CharField(
                default="https://www.youtube.com/watch?v=uwfav6xqBcI", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="waitlist",
            name="subheadline",
            field=models.CharField(default="Subheadline", max_length=200),
        ),
        migrations.AddField(
            model_name="waitlist",
            name="emails",
            field=models.ManyToManyField(to="myapi.email"),
        ),
    ]
