# Generated by Django 4.2.3 on 2023-08-16 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapi", "0006_alter_waitlist_emails"),
    ]

    operations = [
        migrations.AlterField(
            model_name="email",
            name="email_address",
            field=models.EmailField(max_length=254),
        ),
    ]
