[tool.poetry]
name = "mybackend"
version = "0.1.0"
description = ""
authors = ["zjeffreys <zjeffreys@seattlu.edu>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.7"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
